import type { NextPage } from 'next'
import Head from 'next/head'
import LoginForm from '../components/LoginForm/LoginForm'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sign In
        </h1>

        <div className={styles.grid}>
          <LoginForm submit={() => console.log('click')} />
        </div>
      </main>

      <footer className={styles.footer}>

        Created by Monika Patel
        
      </footer>
    </div>
  )
}

export default Home
